 ##
 # Copyright 2017 Gerald Haesendonck
 # Licensed under the Academic Free License version 3.0
 ##

[package]
name = "ntstream"
version = "0.1.0"
authors = ["Gerald Haesendonck <gerald.haesendonck@ugent.be>"]
build = "build.rs"

[build-dependencies]
peg = { version = "0.5" }
